apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.internalPort }}
        volumeMounts:
        - mountPath: /root/bitcoin-node/data/
          name: {{ .Values.data.volumeName }}
        env:
        - name: NETWORK
          value: {{ .Values.NETWORK }}
        - name: INTERNAL_SERVICE
          value: {{ .Values.INTERNAL_SERVICE }}
      volumes:
      - name: {{ .Values.data.volumeName }}
        persistentVolumeClaim:
          claimName: {{ .Values.data.volumeName }}-claim
      {{- if .Values.nodeSelector }}
      tolerations:
        - key: "dedicated"
          operator: "Equal"
          value: "bitcore"
          effect: "NoSchedule"
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      {{- end }}
