replicaCount: 1
image:
  repository: gcr.io/rehive-services/bitcore-node
  tag: latest
  pullPolicy: Always
  command: ''
service:
  name: nginx
  type: NodePort
  externalPort: 80
  internalPort: 3001
ingress:
  enabled: true
  hosts:
    - bitcore-node.s.services.rehive.io
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
  tls:
    - secretName: bitcore-node-tls
      hosts:
        - bitcore-node.s.services.rehive.io
data:
  volumeSize: 500Gi
  gcePersistentDiskName: bitcore-node-data-testnet
  volumeName: bitcore-node-data-testnet
nodeSelector: {cloud.google.com/gke-nodepool: bitcore-node-pool}
