replicaCount: 1
image:
  repository: gcr.io/rehive-services/bitcore-node
  tag: latest
  pullPolicy: Always
  command: 'bitcored'
service:
  name: nginx
  type: NodePort
  externalPort: 3001
  internalPort: 3001
data:
  volumeSize: 500Gi
  gcePersistentDiskName: bitcore-node-data-testnet
  volumeName: bitcore-node-data-testnet
nodeSelector: {cloud.google.com/gke-nodepool: bitcore-node-pool}
